### PR TITLE
Fix `ui.player.destroy()`

### LINKED ISSUE #59: Destroy UI
When calling `.destroy()` on the player while using the UI, errors are thrown. So either the UI should listen for the player destroy event or the UI should expose its own destroy method.

image

### PR DESCRIPTION
**Pull request by MattiasBuelens**
Web UI wasn't correctly removing all its event listeners when THEOplayer is destroyed through `ui.player.destroy()` (where `ui` is a `<theoplayer-default-ui>` or `<theoplayer-ui>`). This caused a whole bunch of errors when those event listeners fire while the player is being destroyed.

React UI now calls `player.destroy()` during unmount, if for some reason that didn't happen yet. (Normally, this happens automatically when the custom element is disconnected from the DOM.)

Fixes #59

### CODE REVIEW

File: src/UIContainer.ts [hunk 1]
```diff
@@ -1065,6 +1056,56 @@ export class UIContainer extends HTMLElement {
...
+        player.removeEventListener('sourcechange', this._onSourceChange);
+        player.removeEventListener(['durationchange', 'sourcechange', 'emptied'], this._updatePlayingAd);
+
+        try {
+            player.theoLive?.removeEventListener('publicationloadstart', this._onSourceChange);
+            player.videoTracks.removeEventListener(['addtrack', 'removetrack', 'change'], this._updateActiveVideoTrack);
+            player.cast?.removeEventListener('castingchange', this._updateCasting);
+            player.ads?.removeEventListener(['adbreakbegin', 'adbreakend', 'adbegin', 'adend', 'adskip'], this._updatePlayingAd);
+        } catch {
+            // Ignore errors from accessing player.ads when the player is already destroyed.
```
Comment (jeroen-tempels) [inline src/UIContainer.ts:1098]: Does this error only occur on the ads? Cause otherwise if it happens on theoLive as well for example, we will still leak the other event listeners and we should add try catches around all of these.

**Review by jeroen-tempels — APPROVED** [review]
